project:
  type: website
  output-dir: docs
  resources: 
    - "~/Desktop/R/personal_website/_site/Swank_Elin_Resume_CV_copy.pdf"

execute:
  freeze: auto

website:
  title: "wander-13"
  navbar:
    left:
      - href: index.qmd
        text: Front Door
      - about.qmd

format:
  html:
    theme:
      - custom_theme.scss
      - cosmo
    css: styles.css
    toc: true

editor: visual

